name: Test and build
on:
  push:
    branches: [main]
    tags:
      - "*"

env:
  GO_VERSION: "1.20"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Pull common linter configs
        run: wget -O .golangci.yml https://raw.githubusercontent.com/JenswBE/setup/main/programming_configs/golang/.golangci.yml

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: >-
            --timeout=5m
            --disable noctx
            --exclude 'func name will be used as send.SendEmail'

      - name: Run tests
        run: |
          go test ./...

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags='-extldflags=-static' -o smtp-cli

      - uses: actions/upload-artifact@v3
        with:
          name: smtp-cli
          path: smtp-cli
          if-no-files-found: error
